apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-tracker
  template:
    metadata:
      labels:
        app: speedtest-tracker
    spec:
      containers:
        - name: speedtest-tracker
          image: ghcr.io/alexjustesen/speedtest-tracker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: APP_KEY
              value: base64:SomeRandomStringChangeMe123456789
            - name: DB_CONNECTION
              value: sqlite
            - name: SPEEDTEST_SCHEDULE
              value: "0 */6 * * *"
            - name: DISPLAY_TIMEZONE
              value: America/New_York