apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community-blackbox
  namespace: monitoring
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-blackbox
        namespace: monitoring
      interval: 30m
  install:
    timeout: 10m
  upgrade:
    timeout: 10m
  values:
    serviceMonitor:
      enabled: true