apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../infrastructure/namespaces
  - ../../infrastructure/metallb
  - ../../infrastructure/longhorn
  - ../../apps/n8n
  - ../../apps/homepage
  - ../../apps/homeassistant
  - ../../apps/forgejo
  - ../../apps/proxmox